### PR TITLE
Run full-test-suite.sh instead of individual tests.

### PR DESCRIPTION
**Pull request by defuse**
Bloody hell I had to do all of these things to change one tiny of the server config:

1. Clone this repostiory.
2. Create a branch.
3. Make the change (hoping it works and doesn't have any mistakes)
4. Commit
5. Push the new branch.
6. Go on github and create a pull request.
7. Say this:
    "We're not reviewing bbotzc PRs, so I'm merging it."
8. (TODO) merge it into master.
9. (TODO) ssh into the buildbot
10. (TODO) pull
11. (TODO) copy the master.cfg file.

If my change is incorrect, I have to go all the way back to step 4.

This complexity is making me procrastinate future changes to the buildbot config.

There has to be a simpler way to get the guarantees this process provides. But I'm fine with doing things this way since I think it's just more busywork to change. I just needed to rant. :-)

### CODE REVIEW

**Comment by nathan-at-least** [comment]
Hm...  I'm also doing this process now, although mine is slightly different because I'm deploying my ticket branch to test it live first, then if I'm satisfied with the results, I'll merge and redeploy.

What if we introduce two new features to streamline this process:

First, add a "deploy $BRANCH" button. This could be a shell script in this repo that will do a git fetch of the given branch, copy the files appropriately, and restart buildbot.  Then hopefully deployment could become: ``mosh bbmaster@ci.leastauthority.com ./bbotzc/deploy $BRANCH``. If no branch is given it defaults to ``master``.

Second, if we had another button to launch a vm or container with the current directory then test builds locally, then we could do this prior to committing or creating a PR.  This might be overkill for now.

What do you think?

I *still* think doing PRs is valuable because we have this list of changes to our buildbot deploy: https://github.com/Electric-Coin-Company/bbotzc/pulls?q=is%3Apr+is%3Aclosed

**Comment by zookoatleastauthoritycom** [comment]
A cool way to make buttons like that is to use foolscap's "flappserver". It
is a POLA way to do it, so that then you can give some computer (for
example a buildslave) the ability to push the button without giving it an
ssh/mosh login on the server in question.

**Comment by nathan-at-least** [comment]
@zookoatleastauthoritycom Thanks for the idea. I definitely prefer that over putting "ssh" *inside* any scripts.

I'd like two pieces though: first is called something like "deploy-here.sh" that takes care of deployment locally. If this were in place, we *could* ssh in and run that. A flappserver could be the second step. I'll add tickets.

**Comment by zookoatleastauthoritycom** [comment]
That's right. The flappserver is only for replacing the "ssh in and run the
script" functionality with a capability.

**Pull request merged**
