### PR TITLE
Add EC2LatentBuildSlave to buildbot master cfg

### PR DESCRIPTION
**Pull request by arcalinea**
@ebfull @nathan-at-least Config for buildbot master resulting from pairing session with Sean to set up EC2 latent buildslave

### CODE REVIEW

**Comment by ebfull** [comment]
Woohoo!

**Comment by defuse** [comment]
Wohoo! What class of EC2 instance are we using for this?

**Comment by defuse** [comment]
Is the `sean_pez` keypair on the buildbot server, or are we going to generate a new one?

**Comment by defuse** [comment]
ACK

**Comment by ebfull** [comment]
`sean_pez` is my EC2 key, there's also taylor_qubes. We can switch it out any time we want.

This is using c4.4xlarge.

**Comment by defuse** [comment]
That private key will have to be on the buildbot server for it to work, right? I think we should generate a new key since `sean_pez` might have access to other EC2 instances.

**Comment by ebfull** [comment]
The buildbot server doesn't need any keys. When the instance spins up, it connects to the buildbot server (specifically, ci.z.cash).

**Comment by ebfull** [comment]
To clarify, the reason why `sean_key` appears here is to instruct AWS which key to set up on the server when it launches the instance.

**Pull request merged**
